/** Threading Practice 2
 *  Write a C program that creates two threads to run the Fibonacci and the Runner 
 *  processes. Threads will indicate the start and the end of their work by printing 
 *  statements in the format “Thread K Starting” “Thread K Finished”, where K is the 
 *  thread number. When the threads finish, the parent thread will output the 
 *  results generated by the two threads by printing in the format, “The sum of first
 *  5 numbers is: 15” and “The first 5 numbers in the Fibonacci sequence are: 
 *  0, 1, 1, 2, 3” if the user had input 5 as the value of N.
*/

#include <stdio.h>
#include <pthread.h>
#include <sys/types.h>
#include <unistd.h>
#include <stdlib.h>

// Global variables
int sum = 0;
int* fib_seq;

// Prints error message and error number
void err_thread(int err)
{
    printf("%d - Thread error\n", err);
}

// Recursive function to calculate sum of n terms in fibonnaci sequence
int fibonacciFn(int n)
{
    if (n <= 1)
    {
        return n;
    }
    return fibonacciFn(n-1) + fibonacciFn(n-2);;
}

// Thread function to print first n terms of the fibonnacci sequence
void *thr_fn_fib(void *arg)
{
    // Printing thread starting
    printf("Thread %lu starting\n", (unsigned long)pthread_self());
    // Getting parameter
    int *nptr = (int*)arg;
    int n = *nptr;

    // Allocating / setting size of array to n
    fib_seq = (int*)malloc(n * sizeof(int));
    // Filling array with each term in sequence
    for (int i = 0; i < n; i++)
    {
        fib_seq[i] = fibonacciFn(i);
    }

    // Printing the sequence
    printf("The first %d numbers in the Finbonacci sequence are: ", n);
    for (int i = 0; i < n - 1; i++)
    {
        printf("%d, ", fib_seq[i]);
    }
    printf("%d\n", fib_seq[n-1]);

    // Printing thread finished
    printf("Thread %lu finished\n", (unsigned long)pthread_self());
    return ((void *)0);
}

// Thread function to print sum of first n numbers
void *runner(void *arg)
{
    // Printing thread starting
    printf("Thread %lu starting\n", (unsigned long)pthread_self());
    // Getting parameter
    int *nptr = (int*)arg;
    int n = *nptr;

    // Summing numbers up to n
    for (int i = 0; i <= n; i++)
        sum += i;
    // Printing sum
    printf("The sum of first %d numbers is: %d\n", n, sum);

    // Printing thread finished
    printf("Thread %lu finished\n", (unsigned long)pthread_self());
    return ((void *)0);
}

int main(int argc, char *arg[])
{
    int n;
    // Getting user input for n
    printf("Enter n: ");
    int check = scanf("%d", &n);
    // If check is not equal to 1, user did not input an integer
    if (check != 1)
    {
        printf("Error: Incorrect input format. Must be an integer.");
        exit(0);
    }
    // If n < 1, user did not input a positive integer
    if (n < 1)
    {
        printf("Error: No number less than 1 is allowed.");
        exit(0);
    }
    

    int err;
    // Creating pthread for fibonnacci sequence
    pthread_t fib_thread;
    // Creating the thread with the thread id
    err = pthread_create(&fib_thread, NULL, thr_fn_fib, (void *)&n);
    // If there was an error in creating the thread, print error message
    if (err != 0)
        err_thread(err);
    sleep(1);

    // Creating pthread for runner
    pthread_t runner_thread;
    // Creating the thread with the thread id
    err = pthread_create(&runner_thread, NULL, runner, (void *)&n);
    if (err != 0)
        err_thread(err);
    sleep(1);

    return 0;
}
